### PR TITLE
add tispark service and its Dockerfile

### LINKED ISSUE #9: should add TiSpark support
It's not that hard, I've done that in my labtop (in a dirty way...):

0. put spark-2.11 and tispark's into ./data directory
1. add a jvm image to compose file and `docker-compose run jvm /bin/bash`
2. cd /data/spark/bin; ./spark-shell

### PR DESCRIPTION
**Pull request by tennix**
This PR closes #9, it adds TiSpark service in docker-compose and its Dockerfile. PTAL @zhexuany @c4pt0r 

*Note*: I've changed docker images from DockerHub to UCloud docker registry to make docker-compose easier up and running in China. @zhexuany You can test it if TiSpark works as expected. If it's ok, I'll change it back to DockerHub before this PR is merged

### CODE REVIEW

**Comment by tennix** [comment]
spark-shell fails on host machine
```
$ spark-shell --master spark://127.0.0.1:7077
scala> import org.apache.spark.sql.TiContext
scala> val ti = new TiContext(spark)
18/05/09 16:22:27 WARN ManagedChannelImpl: [io.grpc.internal.ManagedChannelImpl-1] Failed to resolve name. status=Status{code=UNAVAILABLE, description=null, cause=java.net.UnknownHostException: pd0: Name or serv
ice not known                                                                                                                                                                                                     
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)                               
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)                                           
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)              
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) 
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)                          
        at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:325)
        at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:156)                                          
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)             
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                           
        at java.lang.Thread.run(Thread.java:748)                                                                                    
}                                                                                                                              
18/05/09 16:22:27 WARN PDClient: failed to get member from pd server.                                                               
io.grpc.StatusRuntimeException: UNAVAILABLE                                                                                                                                                
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)                                                                                                                                 
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)                                                                                                                                            
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)                                                                                                                                       
        at com.pingcap.tikv.kvproto.PDGrpc$PDBlockingStub.getMembers(PDGrpc.java:694)                                                                                                                              
        at com.pingcap.tikv.PDClient.getMembers(PDClient.java:223)                 
        at com.pingcap.tikv.PDClient.initCluster(PDClient.java:306)                                                                                                                                               
        at com.pingcap.tikv.PDClient.createRaw(PDClient.java:325)                                                                                                                                                 
        at com.pingcap.tikv.TiSession.getPDClient(TiSession.java:71)                                                   
        at com.pingcap.tikv.TiSession.getTimestamp(TiSession.java:55)                                                  
        at com.pingcap.tikv.TiSession.createSnapshot(TiSession.java:59)                                     
        at com.pingcap.tikv.TiSession.lambda$getCatalog$0(TiSession.java:84)                        
        at com.pingcap.tikv.catalog.Catalog.<init>(Catalog.java:113)                                                                   
        at com.pingcap.tikv.TiSession.getCatalog(TiSession.java:86)                                                                   
        at org.apache.spark.sql.TiContext.<init>(TiContext.scala:38)                                   
        at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:24)                  
        at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:29)                      
        at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:31)                                                               
        at $line15.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:33)                                                                                                                                             
        at $line15.$read$$iw$$iw$$iw$$iw.<init>(<console>:35)                                                                                                                                                 
        at $line15.$read$$iw$$iw$$iw.<init>(<console>:37)                                                                                                                                                     
        at $line15.$read$$iw$$iw.<init>(<console>:39)        
        at $line15.$read$$iw.<init>(<console>:41)                          
        at $line15.$read.<init>(<console>:43)                              
        at $line15.$read$.<init>(<console>:47)                                                                                                                                                                  
        at $line15.$read$.<clinit>(<console>)                                                                                                                                                                   
        at $line15.$eval$.$print$lzycompute(<console>:7)                                                                                                                                                        
        at $line15.$eval$.$print(<console>:6)                                               
        at $line15.$eval.$print(<console>)                                     
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                            
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                                       
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)                                                                                                                                  
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)                                                                        
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at org.apache.spark.repl.Main$.doMain(Main.scala:69)
        at org.apache.spark.repl.Main$.main(Main.scala:52)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.UnknownHostException: pd0: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at io.grpc.internal.DnsNameResolver$JdkResolver.resolve(DnsNameResolver.java:325)
        at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:156)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.pingcap.tikv.exception.GrpcException: retry is exhausted.
  at com.pingcap.tikv.policy.RetryPolicy.handleFailure(RetryPolicy.java:59)
  at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:82)
  at com.pingcap.tikv.AbstractGRPCClient.callWithRetry(AbstractGRPCClient.java:63)
  at com.pingcap.tikv.PDClient.getTimestamp(PDClient.java:75)
  at com.pingcap.tikv.TiSession.getTimestamp(TiSession.java:55)
  at com.pingcap.tikv.TiSession.createSnapshot(TiSession.java:59)
  at com.pingcap.tikv.TiSession.lambda$getCatalog$0(TiSession.java:84)
  at com.pingcap.tikv.catalog.Catalog.<init>(Catalog.java:113)
  at com.pingcap.tikv.TiSession.getCatalog(TiSession.java:86)
  at org.apache.spark.sql.TiContext.<init>(TiContext.scala:38)
  ... 48 elided
Caused by: java.lang.NullPointerException
  at com.pingcap.tikv.PDClient.getBlockingStub(PDClient.java:284)
  at com.pingcap.tikv.PDClient.getBlockingStub(PDClient.java:58)
  at com.pingcap.tikv.AbstractGRPCClient.lambda$callWithRetry$0(AbstractGRPCClient.java:65)
  at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:76)
  ... 56 more
```

It seems that spark-shell connect pd/tikv directly without spark worker. After adding pd and tikv to host machine /etc/hosts, spark-shell can use TiSpark normally

**Comment by zhexuany** [comment]
@tennix Is error resolved?

**Comment by tennix** [comment]
No, we still can't access TiSpark outside of container. I'll add another PR to allow tidb-cluster using host network without isolation, that way all components can communicate through localhost

**Comment by c4pt0r** [comment]
I worked around it.
docker-compose exec tispark-master  /opt/spark-2.1.1-bin-hadoop2.7/bin/spark-shell

**Comment by c4pt0r** [comment]
I think it's not a big deal. Just for demo, no need to access it outside container.

**Comment by c4pt0r** [comment]
Let me know when you upload to dockerhub

**Pull request merged**
