### PR TITLE
Add support for DM

### LINKED ISSUE #97: Add TiDB DM
Please add support for DM

### PR DESCRIPTION
**Pull request by dveeden**
Closes: #97

I added the two template config files with the logging commented out and copied one of the compose files and added this:
```
  dm-master:
    image: pingcap/dm:latest
    volumes:
      - ./config/dm-master.toml:/dm-master.toml:ro
      - ./logs:/logs
    command:
      - /dm-master
      - --log-file=/logs/dm-master.log
      - --config=/dm-master.toml
    restart: on-failure
  dm-worker0:
    image: pingcap/dm:latest
    volumes:
      - ./config/dm-worker.toml:/dm-worker.toml:ro
      - ./logs:/logs
    command:
      - /dm-worker
      - --log-file=/logs/dm-worker0.log
      - --config=/dm-worker.toml
    restart: on-failure
```
Not sure what else is needed to get this to properly support DM

### CODE REVIEW

**Comment by tisonkun** [comment]
Hi @dveeden, thanks for your pull request! May you add a section of doc how this changes take in effect or at least comment on this pull request?

**Comment by tisonkun** [comment]
.. also cc @kennytm & @alex-quan-001

**Comment by tisonkun** [comment]
This is still a draft and I may not the person to review it :P

**Comment by dveeden** [comment]
They way forward is to use TiUP Playground, TiUP Cluster, Kubernetes or TiDB Cloud.

**Pull request closed without merging**
