### PR TITLE
Mention the end of project

### PR DESCRIPTION
**Pull request by tisonkun**
ref https://github.com/pingcap/tidb-docker-compose/issues/95

### CODE REVIEW

**Review by AstroProfundis — APPROVED** [review]
LGTM

**Comment by alex-quan-001** [comment]
I will be responsible for maintaining this repo

**Comment by tisonkun** [comment]
@alex-quan-001 OK. Then let's keep it active.

If you can write down several ongoing tasks, we can see that the project is under developing and it is possible our contributors take ongoing tasks.

**Comment by lilyjazz** [comment]
> I will be responsible for maintaining this repo

We have deleted related documents in 5.0 and above to avoid misleading users. If you need these documents, you can find the documents in the past version.

**Pull request closed without merging**
