### PR TITLE
Mount `dashboards` into the installer to avoid rebuilding tidb-dashbo…

### PR DESCRIPTION
**Pull request by suzaku**
…ard-installer

### CODE REVIEW

**Comment by tennix** [comment]
Rather than executing dashboard-installer everytime the cluster is bootstrapped, I think it's better to persist the Grafana data by mounting a host directory into Grafana container.

**Comment by suzaku** [comment]
@tennix Agree. It would be much simpler if we could just get rid of the dashboard-installer.

**Comment by tennix** [comment]
There is an approach to using [Grafonnet](https://github.com/grafana/grafonnet-lib) to generate dashboards json files and using Grafana 5.x [provisioning feature](http://docs.grafana.org/administration/provisioning/#datasources). So we can just configure Grafana dashboards statically without having to inject dashboards via API. Would you like to help to resolve this issue?

**Comment by suzaku** [comment]
@tennix Did you mean we could somehow use `Grafonnet` to convert the old dashboards json files to new ones?

**Comment by tennix** [comment]
Yes, the grafonnet is just a helper tool for building dashboard templates. And the generated json dashboards can be used for Grafana static provisioning. This can also help future maintenance, it makes the dashboard templates modification reviewable.

**Comment by tennix** [comment]
@suzaku As static provision dashboard is already implemented in #62. I'll close this PR now.

**Pull request closed without merging**
