### PR TITLE
Make the 5 minute guide to work Linux

### PR DESCRIPTION
**Pull request by iamcharleschege**
The official blog "How To Spin Up an HTAP Database in 5 Minutes with TiDB + TiSpark" is a Mac only guide. This commit allows the same guide to work on Linux.

### CODE REVIEW

**Comment by liufuyang** [comment]
I some how feel this readme is for dev and test this repo, not for making that 5m guide.

Maybe somehere else could be a better place to put a guide for Linux.(and I assume the official guide is not too difficult for any Linux user to follow ) 🤔

**Comment by tennix** [comment]
@iamcharleschege Thank you for your contribution. The README document in this repo is not specific to Mac or Linux. I think it's better to add this tutorial in [docs](https://github.com/pingcap/docs) or [docs-cn](https://github.com/pingcap/docs-cn).
/cc @lilin90

**Comment by lilin90** [comment]
@tennix How about creating a "docs" folder in the tidb-docker-compose repo? Then we can put the two guides "How To Spin Up an HTAP Database in 5 Minutes with TiDB + TiSpark" for macOS and Linux.

@iamcharleschege Thanks! But this file is not suitable to be here. I'll test it and consider putting it to our official blog.

**Comment by iamcharleschege** [comment]
Thanks guys for your feedback. I understand now.

**Pull request closed without merging**
